<html>
<head>
<title>Terms & Conditions</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<style>
body{
	text-align:justify;
}
.copyright {
  padding: 0.3em 1em;
  background-color: #25262e;
}
.footer-menu{
  float: left;
    margin-top: 10px;
}
.footer-menu a{
  color: #cfd2d6;
  padding: 6px;
  text-decoration: none;
}
.footer-menu a:hover, .social i:hover{
  color: #c7940a;
}
.copyright p {
  font-size: 0.9em;
  text-align: right;
}
</style>
</head>

<body>
<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="index.php">GoShop.</a>
	
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Search here</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
		<li class="nav-item">
            <a class="nav-link active" aria-current="page" href="index.php">Go to Home page</a>
          </li>
          
        </ul>
		
        
		<div class="container mt-3">
  
  
  
</div>
      </div>
    </div>
  </div>
</nav>
<!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header"> 
        <h4 class="modal-title">Login</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
		<form method=post action="checkuser.php"> <!-- study about get and post and action method-->
        <table class=="table table-striped">
		<tr><td width=50%>Enter Email Id</td><td><input required type=email name=username></td></tr>
		<tr><td>Enter Password</td><td><input type=password required name=userpass></td></tr>
		<tr ><td ><input type=submit class="btn btn-success" name="Signin"></td>
		<td ><a href="updatepass.php" >Forgot Username or Password?</a></td></tr>
		</table>
		</form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer"><a href="signup.php">Not have an account? Register here</a> 
        <button type="button" class="btn btn-success" data-bs-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div> 
<h4 style="margin-top:100px;margin-left:150px;margin-right:150px;">GoShop's Terms of use</h4>
<p style="margin-left:150px;margin-right:150px;">This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

<p style="margin-left:150px;margin-right:150px;">This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.GoShop.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)</p>

<p style="margin-left:150px;margin-right:150px;">The Platform is owned by GoShop Internet Private Limited, a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 5150103, Karnataka, India and its branch offices at 2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-5150103, Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-5150034, Karnataka, India (hereinafter referred to as "GoShop").</p>

<p style="margin-left:150px;margin-right:150px;">Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with GoShop Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with GoShop</p>

<p style="margin-left:150px;margin-right:150px;">For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. GoShop allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean GoShop Internet Private Limited.</p>

<p style="margin-left:150px;margin-right:150px;">ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by GoShop Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.</p>

<h5 style="margin-left:150px;margin-right:150px;">Membership Eligibility</h5>

<p style="margin-left:150px;margin-right:150px;">Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent or legal guardian.

</p>
<p style="margin-left:150px;margin-right:150px;">As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. GoShop reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to GoShop's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.

</p>
<h5 style="margin-left:150px;margin-right:150px;">Your Account and Registration Obligations</h5>
<p style="margin-left:150px;margin-right:150px;">If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.</p>

<p style="margin-left:150px;margin-right:150px;">Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.</p>

<p style="margin-left:150px;margin-right:150px;">You agree that GoShop shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.

If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences there from.

You must maintain confidentiality of the account information and for all the activities that occur under Your account. You must not share your login details, ie, username and password of Your account with any other person, else it would be considered breach of this Terms of Use.

You agree to: (a) ensure that You successfully log out from Your account at the end of each session; and (b) immediately notify GoShop of any unauthorized use of Your account. If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may request You to change the password or we may suspend Your account without any liability to GoShop, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.

You will have access to other apps owned by GoShop group companies through the same login username and password. You agree to have single login access to all the apps owned by GoShop group companies.</p>

<h5 style="margin-left:150px;margin-right:150px;">Payment Facility for Buyers:
</h5>
<ul style="margin-left:150px;margin-right:150px;line-height:200%;">
<li>You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Seller to purchase the products and /or services from the Seller using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Seller using Payment Facility.</li>
<li>You, as a Buyer, may agree with the Seller through electronic communication and electronic records and using the automated features as may be provided by Payment Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of Dispatch / Delivery time or subsequent novation / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.</li>
<li>You, as a Buyer, shall electronically notify Payment Facility using the appropriate GoShop Platform features immediately upon Delivery or non- Delivery within the time period as provided in Policies. Non notification by You of Delivery or non- Delivery within the time period specified in the Policies shall be construed as a deemed Delivery in respect of that Transaction. In case of Cash- On Delivery transactions, Buyer is not required to confirm the receipt of products or services.</li>
<li>You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using Platform features within the stipulated time than this would make You ineligible for a refund.</li>
<li>You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services</li>
<li>Except for Cash On Delivery transaction, refund, if any, shall be made at the same Issuing Bank from where Transaction Price was received, or through any other method available on the Platform, as chosen by You.</li>
<li>For Cash On Delivery transactions, refunds, if any, will be made via electronic payment transfers.</li>
<li>Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.</li>
<li>For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved by Reserve Bank India (RBI).
</li>
<li>Refunds may be supported for select banks. Where a bank is not supported for processing refunds, You will be required to share alternate bank account details with us for processing the refund.
</li>
<li>Refund shall be conditional and shall be with recourse available to GoShop in case of any misuse by Buyer.
</li>
<li>We may also request you for additional documents for verification.
</li>
<li>The Buyer and Seller acknowledge that GoShop will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in processing a Transaction/Transaction Price which is beyond control of GoShop.
</li>
</ul>
<h5 style="margin-left:150px;margin-right:150px;">Other Businesses
</h5>
<p style="margin-left:150px;margin-right:150px;">GoShop does not take responsibility or liability for the actions, products, content and services on the Platform, which are linked to Affiliates and / or third party Platforms using Platform's APIs or otherwise. In addition, the Platform may provide links to the third party Platforms of Our affiliated companies and certain other businesses for which, GoShop assumes no responsibility for examining or evaluating the products and services offered by them. GoShop do not warrant the offerings of, any of these businesses or individuals or the content of such third party Platform(s). GoShop does not endorse, in any way, any third party Platform(s) or content thereof.</p>

<br><br>
<div class="row copyright">
  <div class="footer-menu">

  <a href="index.php">Home</a>
  <a href="">F.A.Q</a>
  <a href="privacyPolicy.php">Cookies Policy</a>
  <a href="termsConditions.php">Terms Of Service</a>
  <a href="support.php">Support</a>

  </div>
   <p class="copyright">Copyright &copy; 2023</p>
</div>
</body>


</html>